### ISSUE TITLE
Instances issue with AWS

### ISSUE THREAD

**Issue by NtHawk101** [Sy14r/Cryptbreaker#8]
I now get all the way to the point where I select attempt to crack but still receive an error stating "Job failed - Need to configure Spot Instances in AWS." The database I am using is very small so I'm not understanding why I need to do this. Nevertheless, I configured spot instances and requested the increase. I get a little bit of round around from AWS before they think they have it configured only to then be told I need to  "Please launch a t2.micro EC2 instance in the desired region to activate it.
Once region is active we can increase your Spot limits." I'm not an AWS guy so I'm a little lost on why I need to do this and how, not to mention there is no mention of this need here in the guidance provided. 
Is anyone else seeing this issue or is it just me?

**Comment by Sy14r** [comment]
NtHawk101,

Thanks for the update. I'll your answer you immediate questions first.

All cracking occurs in AWS so you need to have the account setup with the proper permissions and instance limits to enable use of the cloud resources. I've never had AWS tell me they required a t2.micro instance in a region before upping limits for me so that could be a new step in their troubleshooting/customer service playbook.

I will acknowledge that the initial setup instructions could could use some tlc and since you've brought this to my attention I will work to make sure that the quick start guide covers these topics and more, and I will work to automate the process of automatically launching a t2.micro instance in each region as part of initial setup.

The issues you're encountering are a one-time initial setup hurdle that should not be required once you have spot instance limits increased. As for how to launch the t2.micro instances they want you to, this blog has a good walkthrough (you can do everything up to connecting to the ec2 instance) https://medium.com/@praneeth.jm/launching-and-connecting-to-an-aws-ec2-instance-6678f660bbe6

If you can wait for ~24-48 hours I'll update our own documentation to better answer these questions instead of having you rely on the external blog I linked and I'll add a step to the intial setup to create and then remove t2.micro instances automatically for you.

**Comment by Sy14r** [comment]
Also, just an additional note as to why this is an inconsistent issue. This is a snippet from Amazon's AWS documentation:

> Spot Instance limits are dynamic. When your account is new, your limit might be lower than 20 to start, but can increase over time. In addition, your account might have limits on specific Spot Instance types. If you submit a Spot Instance request and you receive the error Max spot instance count exceeded, you can complete the AWS Support Center Create case form to request a Spot Instance limit increase. For Limit type, choose EC2 Spot Instances. For more information, see Amazon EC2 Service Limits

Some accounts will not have to increase the spot limit limitations on their account and others will. I'll work to improve documentation around the process for people who run into the issue.

**Comment by Sy14r** [comment]
Wanted to let you know. I created a brand new AWS account tied to a new email and went through the initial setup process. They haven't asked me to run any t2.micro instances yet (the final request is still being serviced) but I did document the steps in more detail and post to the project wiki [here](https://github.com/Sy14r/Cryptbreaker/wiki/Spot-Limit-Increase-Walkthrough)

Let me know if that helps. I'd review your current case to make sure it closely matches what is documented there to see if maybe some difference resulted in them making that request.
